
echo "------------Q1---------------"
sqlite3 bbd.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"
sqlite3 bbd_1.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"
sqlite3 bbd_10.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"
sqlite3 bbd_100.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"
sqlite3 bbd_1000.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"
sqlite3 bbd_10000.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q1.sql"

echo "------------Q2---------------"
sqlite3 bbd.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"
sqlite3 bbd_1.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"
sqlite3 bbd_10.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"
sqlite3 bbd_100.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"
sqlite3 bbd_1000.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"
sqlite3 bbd_10000.db < "/home/mbaxqll4/Documents/QueryingData/Week3/DB/Q2.sql"

echo "------------Q3---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q3.sql"

echo "------------Q4---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q4.sql"

echo "------------Q5---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q5.sql"

echo "------------Q6---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql"
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql" 
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q6.sql"

echo "------------Q7---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql" 
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql"
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q7.sql"

echo "------------Q8---------------"
sqlite3 bbd.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql"
sqlite3 bbd_1.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql"
sqlite3 bbd_10.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql" 
sqlite3 bbd_100.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql"
sqlite3 bbd_1000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql"
sqlite3 bbd_10000.db ".read /home/mbaxqll4/Documents/QueryingData/Week3/DB/Q8.sql"


